# fly.toml app configuration file generated for datomic-browser on 2024-12-09T13:39:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'electric3-datomic-browser'
primary_region = 'ewr'

[env]
  PORT = '8080'

[processes]
  app = './prod.sh'

[build.args]
  HYPERFIDDLE_FIDDLE_NS="datomic-browser.mbrainz-browser"
  HYPERFIDDLE_FIDDLE_DEPS_ALIAS="datomic-browser"

[http_service]
  internal_port = 8080
  force_https = true
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 8
