app = "ui-demo"
primary_region = "ewr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[build.args]
  HYPERFIDDLE_DOMAIN="ui-demo"


# NO_COLOR=1 fly deploy --config src/ui_demo/fly.toml --remote-only --build-only

# fly scale vm shared-cpu-8x --config src/ui_demo/fly.toml
# fly scale show  --config src/ui_demo/fly.toml
# fly status --config src/ui_demo/fly.toml